### PR TITLE
Update PvPstatsAnnouncer.cpp

### PR DESCRIPTION
**Pull request by Winfidonarleyan**

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
Why is this repo not in the Module group?

**Comment by Kitzunu** [comment]
@FrancescoBorzi can you add this repo to the modules group

**Comment by Helias** [comment]
done ✅ it should appear soon

**Review by Kitzunu — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
```
src/PvPstatsAnnouncer.cpp:60:89: fatal error: no member named 'GetString' in 'Field'
                        OutputGlobal(Acore::StringFormatFmt("{}. {} - {}", i, fields[2].GetString(), fields[1].GetUInt32()));
```

**Pull request merged**
